### PR TITLE
Upgrade to Gradle 7 and publish to Nexus

### PR DESCRIPTION
**Pull request by robertpanzer**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

[ ] Bug fix
[ ] New non-breaking feature
[ ] New breaking feature
[ ] Documentation update
[x] Build improvement

## Description

This PR updates grade to the latest version and changes the publishing to publish to Sonatype.
Apparently I had forgotten yet to make these changes for this repo.

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by maxandersen** [comment]
for what it is worth this PR enables me to run `gradle publishToMavenLocal` which is a big win for me ;)

**Comment by robertpanzer** [comment]
Awesome, thanks for letting me know.
That takes the pressure from me to release immediately.

**Comment by maxandersen** [comment]
> That takes the pressure from me to release immediately.

noooooooooo.....:) would love a release in maven central or even snapshot repo if at all possible.

but yeah, I can survive for now.

**Comment by robertpanzer** [comment]
@maxandersen I staged a release at https://oss.sonatype.org/content/repositories/orgasciidoctor-1289
It would be great if you could try out that repository.

**Comment by maxandersen** [comment]
works great for me using this jbang script:

```
///usr/bin/env jbang "$0" "$@" ; exit $?
/* can run faster this way - but not a requirement */
//JAVA 17+
//JAVA_OPTIONS --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED
//DEPS org.asciidoctor:asciidoctorj:2.5.3
//DEPS org.asciidoctor:asciidoctorj-diagram:2.2.1

////REPOS mavencentral,jitpack
////DEPS com.github.asciidoctor:asciidoctorj-reveal.js:main-SNAPSHOT

//REPOS mavencentral,https://oss.sonatype.org/content/repositories/orgasciidoctor-1289
//DEPS org.asciidoctor:asciidoctorj-revealjs:5.0.0.rc1


import org.asciidoctor.Asciidoctor;
import org.asciidoctor.Attributes;
import org.asciidoctor.AttributesBuilder;
import org.asciidoctor.Options;
import org.asciidoctor.SafeMode;
import org.asciidoctor.log.LogHandler;
import org.asciidoctor.log.LogRecord;

import java.io.File;

public class adoc2reveal {

    public static void main(String... args) {
        File file = args.length>1 ? new File(args[0]) : new File("index.adoc");
        
        Asciidoctor asciidoctor = Asciidoctor.Factory.create();

        asciidoctor.registerLogHandler(new LogHandler() {
            @Override
            public void log(LogRecord logRecord) {
                System.out.println(logRecord.getMessage());
            }
        });
        asciidoctor.requireLibrary("asciidoctor-revealjs");
        asciidoctor.requireLibrary("asciidoctor-diagram");
        asciidoctor.convertFile(file,
                Options.builder()
                        .backend("revealjs")
                        .safe(SafeMode.UNSAFE)
                        .attributes(
                                Attributes.builder()
                                        .attribute("revealjsdir", "https://cdn.jsdelivr.net/npm/reveal.js@4.3.1")
                                        .build()
                        ).build()
        );
    }
}
```

**Comment by maxandersen** [comment]
as you can see in the commented out //REPOS and //DEPS could use it via jitpack after you merged the sonatype change. before that jitpack failed on signing requirement too - so good all round fixes and I can finish up my script and make a revealjs  toolchain requiring zero maven/java/ruby etc setup :)

**Comment by robertpanzer** [comment]
Beautiful!
I just hit the release button in Sonatype, so it should hit Maven central very soon.

Thank you so much!

**Pull request merged**
